### ISSUE TITLE
Task 4.4: Add a non-domain user account to VPN Security group

### ISSUE THREAD

**Issue by Anghus** [HoneycuttInc/Warkworth#4]
Exercise 4, Task 4: It is not clear why the user account Mark is listed on the template security groups explicitly. He is also part of other security groups that are listed in that section. Adding a non-domain user account to the security groups with permissions to enroll the VPN certificate will illustrate better how to allow regular users to connect to the VPN server.

**Comment by networkingguru** [comment]
Done, kind of. I wrote a lengthy explanation for why we are doing this, but I did not add a non-domain user to the VPN Users group, largely because I could not figure out what object type to add. My recollection is that contact objects have no ability to be listed in an ACL due to them lacking a SID, and I have very little experience with the InetOrgPerson object.
